### PR TITLE
Add new methods, property and the test.

### PR DESCRIPTION
**Pull request by LI-NA**
Change handelMessage into method.
Add reconnecting property, getLastMessageId and removeOutgoingMessage methods because it is on MQTT.js API document.
Change the order of methods.
Add new test using getLastMessageId.

ps. Is removeOutgoingMessage really used? I just add it because I can find it on MQTT.js document, but I never use it before. My purpose is just getLastMessageId.

### CODE REVIEW

**Comment by RangerMauve** [comment]
Sweet, that looks good. Could you elaborate a bit on why you changed `handleMessage` into a method?

**Comment by LI-NA** [comment]
Oh, maybe I'm wrong. The `handleMessage` must be property because it can be overwrited... I just read the document incorrectly.

**Comment by RangerMauve** [comment]
Awesome. Thank you for the PR! :D

**Comment by RangerMauve** [comment]
Published in 2.3.0

**Pull request merged**
