### PR TITLE
use single quotes only

### PR DESCRIPTION
**Pull request by Tabrizian**
The file used a mixture of single quotes and double quotes. By now it will use only single qoutes.

### CODE REVIEW

**Comment by RangerMauve** [comment]
Would you be willing to add an eslint config of some sort to ensure future development has that automatically?

**Comment by Tabrizian** [comment]
Sure I'll do it as soon as possible. What's your idea about default configuration? Default config for ```eslint``` would suffice?

**Comment by RangerMauve** [comment]
Thank you!
I think the best approach would be to keep it consistent with [mqtt.js](https://github.com/mqttjs/MQTT.js) to make it easier for people to switch between both.

**Comment by Tabrizian** [comment]
Yeah, that’s a great idea. I’ll do it. 🙌🏻

On Oct 10, 2017, at 5:25 PM, RangerMauve <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you!
I think the best approach would be to keep it consistent with mqtt.js<https://github.com/mqttjs/MQTT.js> to make it easier for people to switch between both.

**Comment by RangerMauve** [comment]
Thank you! Would you be interested in becoming a collaborator for the project?

**Comment by Tabrizian** [comment]
Yes, of course. Why not. :heart_eyes:

**Comment by Tabrizian** [comment]
Linting is finished based on ```MQTT.js``` lint file.

**Comment by RangerMauve** [comment]
Awesome! You can merge it in when you've accepted the invite. Could I get your NPM username so I can give you publish rights?

**Comment by Tabrizian** [comment]
Sure, my username is ```tabrizian```.  You're really welcoming. Thank you very much. :raised_hands:

**Comment by RangerMauve** [comment]
Thank you for contributing! Since this isn't a functional change, I'm thinking we could release it on npm for the next change, unless you think this will change performance or something.
I've added you  as a collaborator on npm in the meantime. :D

**Comment by Tabrizian** [comment]
Yes, I agree with you. We can wait for the next release to publish them. 
Thank you for your support! Is there any slack channel or something like that to discuss issues more throughly?

**Comment by RangerMauve** [comment]
No that I know, there might be one for the main MQTT.js repo, but I find github issues are more than enough for small projects.
If you have some ideas for changes, just put in a new issue and that'll also let other people get instant insight as to what's going on.
If you wanna reach me directly, my email is in my github bio.

**Comment by Tabrizian** [comment]
Oh, thanks. You're right. GitHub issues would suffice.

**Pull request merged**
